name: VideoAnnotator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ffmpeg  # Essential for video processing
  - cmake   # For building native extensions
  - pkg-config
  - pip:
    - -r requirements.txt
