name: babyjokes4
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cuda-cccl=12.2.140
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.2.140
  - cuda-opencl-dev=12.2.140
  - cuda-profiler-api=12.2.140
  - cuda-runtime=12.1.0
  - cycler=0.12.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - eigen=3.4.0
  - executing=0.8.3
  - ffmpeg=4.2.3
  - filelock=3.9.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imageio=2.31.5
  - imageio-ffmpeg=0.4.9
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - lerc=3.0
  - libclang=12.0.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.3.141
  - libcurand-dev=10.3.3.141
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libogg=1.3.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - moviepy=1.0.3
  - mpmath=1.3.0
  - munkres=1.1.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - opencv=4.6.0
  - openjpeg=2.4.0
  - openssl=3.0.11
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - platformdirs=3.10.0
  - proglog=0.1.9
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=305
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.31.0
  - scipy=1.11.3
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ultralytics=8.0.197
  - urllib3=1.26.16
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - torchaudio==2.1.0
      - torchvision==0.16.0
