"""API endpoints for accessing job artifacts.

This module provides endpoints for listing and downloading artifacts
generated by pipelines.
"""

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from videoannotator.api.database import get_storage_backend
from videoannotator.api.middleware.auth import validate_api_key
from videoannotator.services.artifacts import get_annotation_artifacts
from videoannotator.storage.manager import provider_for_job
from videoannotator.utils.compression import create_job_zip_archive
from videoannotator.utils.logging_config import get_logger

logger = get_logger("api.artifacts")

router = APIRouter()


@router.get("/{job_id}/artifacts")
async def download_job_artifacts(
    job_id: str,
    current_user=Depends(validate_api_key),
):
    """Download all artifacts for a specific job as a ZIP archive.

    Args:
        job_id: The unique identifier of the job.
        current_user: The authenticated user.

    Returns:
        StreamingResponse: A ZIP file containing the artifacts.
    """
    try:
        # Get list of artifacts to download
        try:
            job = get_storage_backend().load_job_metadata(job_id)
        except Exception:
            job = None
        recorded = job.storage_path if job else None
        provider = provider_for_job(job_id, recorded)
        artifacts = get_annotation_artifacts(job_id, provider)

        if not artifacts:
            raise HTTPException(
                status_code=404, detail=f"No artifacts found for job {job_id}"
            )

        # Create generator for ZIP file
        zip_generator = create_job_zip_archive(job_id, artifacts, provider)

        # Return streaming response
        return StreamingResponse(
            zip_generator,
            media_type="application/zip",
            headers={
                "Content-Disposition": f"attachment; filename=job_{job_id}_artifacts.zip"
            },
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error downloading artifacts for job {job_id}: {e}")
        raise HTTPException(
            status_code=500, detail="Internal server error while preparing download"
        ) from e
