"""API endpoints for accessing job artifacts.

This module provides endpoints for listing and downloading artifacts
generated by pipelines.
"""

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse

from videoannotator.api.database import get_storage_backend
from videoannotator.api.middleware.auth import validate_api_key
from videoannotator.results_folder import result_files_in, run_folder_of
from videoannotator.services.artifacts import get_annotation_artifacts
from videoannotator.storage.manager import provider_for_job
from videoannotator.storage.providers.base import ArtifactType
from videoannotator.utils.compression import create_job_zip_archive, stream_zip
from videoannotator.utils.logging_config import get_logger

logger = get_logger("api.artifacts")

router = APIRouter()


@router.get("/{job_id}/artifacts")
async def download_job_artifacts(
    job_id: str,
    include_video: bool = Query(
        False,
        description="Also include the job's video. Off by default since spec 022: "
        "the zip was otherwise one more copy of sensitive video.",
    ),
    current_user=Depends(validate_api_key),
):
    """Download a job's results as a ZIP archive, without its video by default.

    Args:
        job_id: The unique identifier of the job.
        include_video: Also include the video.
        current_user: The authenticated user.

    Returns:
        StreamingResponse: A ZIP file containing the artifacts.
    """
    try:
        try:
            job = get_storage_backend().load_job_metadata(job_id)
        except Exception:
            job = None
        headers = {
            "Content-Disposition": f"attachment; filename=job_{job_id}_artifacts.zip"
        }
        if not include_video:
            headers["X-VideoAnnotator-Notice"] = (
                "video excluded; use include_video=true"
            )

        if job is not None and run_folder_of(job) is not None:
            # Spec 022: results live in the job's results folder.
            folder = Path(str(job.output_dir))
            entries = [
                (p, p.relative_to(folder).as_posix()) for p in result_files_in(folder)
            ]
            video = Path(job.video_path) if job.video_path else None
            if include_video and video is not None and video.is_file():
                entries.append((video, video.name))
            if not entries:
                raise HTTPException(
                    status_code=404, detail=f"No artifacts found for job {job_id}"
                )
            return StreamingResponse(
                stream_zip(entries), media_type="application/zip", headers=headers
            )

        recorded = job.storage_path if job else None
        provider = provider_for_job(job_id, recorded)
        artifacts = [
            a
            for a in get_annotation_artifacts(job_id, provider)
            if include_video or a.artifact_type != ArtifactType.VIDEO
        ]

        if not artifacts:
            raise HTTPException(
                status_code=404, detail=f"No artifacts found for job {job_id}"
            )

        return StreamingResponse(
            create_job_zip_archive(job_id, artifacts, provider),
            media_type="application/zip",
            headers=headers,
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error downloading artifacts for job {job_id}: {e}")
        raise HTTPException(
            status_code=500, detail="Internal server error while preparing download"
        ) from e
