"""Base storage provider interface.

This module defines the abstract base class for storage providers and
related data structures.
"""

from abc import ABC, abstractmethod
from collections.abc import Iterator
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import BinaryIO


class ArtifactType(str, Enum):
    """Types of artifacts generated by pipelines."""

    VIDEO = "video"
    ANNOTATION = "annotation"
    REPORT = "report"
    LOG = "log"
    OTHER = "other"


@dataclass
class JobArtifact:
    """Represents a file stored in the job storage."""

    job_id: str
    path: str  # Relative path within the job directory
    name: str
    size_bytes: int
    artifact_type: ArtifactType


class StorageProvider(ABC):
    """Abstract base class for storage providers."""

    @abstractmethod
    def initialize(self) -> None:
        """Initialize the storage provider (e.g., create root dir)."""
        pass

    @abstractmethod
    def create_job_dir(self, job_id: str) -> None:
        """Create a directory for a specific job.

        Args:
            job_id: The unique identifier of the job.
        """
        pass

    @abstractmethod
    def save_file(self, job_id: str, relative_path: str, content: BinaryIO) -> str:
        """Save a file to the job storage.

        Args:
            job_id: The unique identifier of the job.
            relative_path: Path relative to the job directory.
            content: File content as a binary stream.

        Returns:
            str: The absolute path or URL of the saved file.
        """
        pass

    @abstractmethod
    def get_file(self, job_id: str, relative_path: str) -> BinaryIO:
        """Open a file for reading.

        Args:
            job_id: The unique identifier of the job.
            relative_path: Path relative to the job directory.

        Returns:
            BinaryIO: File content as a binary stream.
        """
        pass

    @abstractmethod
    def list_files(self, job_id: str) -> Iterator[JobArtifact]:
        """List all files for a specific job.

        Args:
            job_id: The unique identifier of the job.

        Returns:
            Iterator[JobArtifact]: Iterator of artifact objects.
        """
        pass

    @abstractmethod
    def exists(self, job_id: str, relative_path: str) -> bool:
        """Check if a file exists.

        Args:
            job_id: The unique identifier of the job.
            relative_path: Path relative to the job directory.

        Returns:
            bool: True if the file exists, False otherwise.
        """
        pass

    @abstractmethod
    def get_absolute_path(self, job_id: str, relative_path: str) -> Path:
        """Get the absolute local path of a file (if applicable).

        Note: This may raise NotImplementedError for cloud providers that
        don't have a local representation.

        Args:
            job_id: The unique identifier of the job.
            relative_path: Path relative to the job directory.

        Returns:
            Path: Absolute local path.
        """
        pass
