# LAION Pipelines Configuration for VideoAnnotator Batch Processing

# Default LAION pipeline configurations
laion_face_analysis:
  model_size: "small"           # "small" or "large" - large is faster with GPU
  confidence_threshold: 0.6     # Face detection confidence threshold
  top_k_emotions: 5             # Number of top emotions to return
  device: "auto"                # "cpu", "cuda", or "auto"
  face_detection_backend: "opencv"
  min_face_size: 30
  max_faces: 10
  include_raw_scores: false
  model_cache_dir: "./models/laion_face"

laion_voice_analysis:
  model_size: "small"           # "small" or "large" - large is faster with GPU
  whisper_model: "mkrausio/EmoWhisper-AnS-Small-v0.1"
  cache_dir: "./models/laion_voice"
  
  # Audio processing
  min_segment_duration: 1.0     # Minimum segment length in seconds
  max_segment_duration: 15.0    # Maximum segment length in seconds
  
  # Segmentation strategy
  segmentation_mode: "fixed_interval"  # "fixed_interval", "diarization", "scene_based", "vad"
  segment_overlap: 0.0          # Overlap between segments in seconds
  
  # Integration options
  enable_diarization: false     # Use speaker diarization for segmentation
  enable_scene_alignment: false # Align with scene boundaries
  
  # Output configuration
  include_raw_scores: false
  include_transcription: true   # Include speech transcription
  top_k_emotions: 5             # Number of top emotions to return

# Quality presets for different use cases
fast_preset:
  laion_face_analysis:
    model_size: "small"
    confidence_threshold: 0.7
    top_k_emotions: 3
    max_faces: 5
  laion_voice_analysis:
    model_size: "small"
    min_segment_duration: 2.0
    max_segment_duration: 20.0
    include_transcription: false
    top_k_emotions: 3

balanced_preset:
  laion_face_analysis:
    model_size: "small"
    confidence_threshold: 0.6
    top_k_emotions: 5
    max_faces: 10
  laion_voice_analysis:
    model_size: "small"
    min_segment_duration: 1.0
    max_segment_duration: 15.0
    include_transcription: true
    top_k_emotions: 5

high_quality_preset:
  laion_face_analysis:
    model_size: "large"
    confidence_threshold: 0.5
    top_k_emotions: 5
    max_faces: 15
  laion_voice_analysis:
    model_size: "large"
    min_segment_duration: 1.0
    max_segment_duration: 10.0
    include_transcription: true
    top_k_emotions: 5
    segmentation_mode: "diarization"  # Use advanced segmentation if available
