# OpenFace 3.0 Configuration for VideoAnnotator
# This configuration enables comprehensive facial behavior analysis using OpenFace 3.0

scene_detection:
  enabled: true
  threshold: 0.3
  min_scene_length: 1.0

person_tracking:
  enabled: true
  model_name: 'yolo11s'
  confidence_threshold: 0.5

face_analysis:
  enabled: true
  backend: 'openface3'  # Use OpenFace 3.0 for face analysis
  
  # Model paths (working configuration)
  face_detector_model: "./weights/Alignment_RetinaFace.pth"
  landmark_model: "./weights/Landmark_98.pkl"  # 98-point landmarks (68-point has compatibility issues)
  
  # Detection settings
  detection_confidence: 0.5
  max_faces: 5
  track_faces: true
  
  # Feature extraction settings - COMPREHENSIVE OPENFACE 3.0 ANALYSIS
  landmark_points: 98  # Use 98-point landmarks (working configuration)
  enable_3d_landmarks: true   # Enable 3D facial landmarks
  enable_action_units: true   # Enable Action Units (AU) intensity and presence
  enable_head_pose: true      # Enable head pose estimation (3D orientation)
  enable_gaze: true          # Enable gaze direction estimation  
  enable_emotions: true      # Enable emotion recognition
  
  # Advanced feature settings
  action_units:
    intensity_threshold: 0.5
    presence_threshold: 0.3
    normalize_range: [0, 5]
    
  head_pose:
    angle_units: "degrees"
    coordinate_system: "opencv"
    
  gaze:
    use_head_pose_proxy: true
    confidence_threshold: 0.6
    
  emotions:
    probability_threshold: 0.1
    normalize_probabilities: true
    include_valence_arousal: true
  enable_head_pose: true      # Enable head pose estimation (rotation & translation)
  enable_gaze: true           # Enable gaze tracking and eye gaze direction
  enable_emotions: true       # Enable emotion recognition from facial expressions
  
  # Performance settings
  batch_size: 1
  device: 'cpu'  # 'cpu' or 'cuda' (tested with CPU)
  confidence_threshold: 0.5
  
  # Output settings
  save_landmarks: true
  save_face_crops: false
  save_visualizations: true

audio_processing:
  enabled: true
  whisper_model: 'base'
  sample_rate: 16000

# Processing settings
processing:
  max_workers: 1  # OpenFace 3.0 can be memory intensive
  chunk_size: 1000  # Process videos in chunks to manage memory
