# OpenFace 3.0 Complete Configuration
# Enhanced configuration for all advanced facial behavior analysis features

face_analysis:
  backend: "openface3"
  detection_confidence: 0.7
  landmark_model: "98_point"
  device: "auto"  # auto, cpu, cuda
  max_faces: 5
  
  # Core features (already implemented)
  enable_3d_landmarks: true
  
  # Advanced features (newly implemented)
  enable_action_units: true    # Facial muscle movement analysis
  enable_head_pose: true       # 3D head orientation tracking
  enable_gaze: true           # Eye direction estimation
  enable_emotions: true       # Facial expression classification
  
  # Face tracking
  track_faces: true
  
  # Action Units settings
  action_units:
    intensity_threshold: 0.5     # Minimum intensity to register presence
    presence_threshold: 0.3      # Threshold for AU presence detection
    normalize_range: [0, 5]      # Intensity scale normalization
    
  # Head pose settings  
  head_pose:
    angle_units: "degrees"       # degrees or radians
    coordinate_system: "opencv"  # OpenCV coordinate system
    
  # Gaze settings
  gaze:
    use_head_pose_proxy: true    # Use head pose as gaze direction proxy
    confidence_threshold: 0.6    # Minimum confidence for gaze detection
    
  # Emotion settings
  emotions:
    probability_threshold: 0.1   # Minimum probability to include emotion
    normalize_probabilities: true  # Apply softmax normalization
    include_valence_arousal: true  # Calculate valence/arousal dimensions

# Output settings
output:
  format: "coco"
  include_detailed_results: true
  save_face_crops: false
  
# Performance settings
performance:
  batch_size: 1
  optimize_memory: true
  enable_gpu_acceleration: true
